<<<<<<< HEAD
# CI de Níivel 01 - Disparo manual a partir de 1 clique

# nome que vai aparecer lá nas opções de pipe

name: 'Execução Manual'

# triggers OU gatilhos de execução
  # Gatilho de execução manual = workflow_dispatch

on:
  workflow_dispatch:

jobs:

  #descrição do job
  e2e-tests:

    # maquina que o job vai executar
    runs-on: ubuntu-latest

    # passo a passo das acoes do job    
    steps: 

      - uses: actions/checkout@v4

     # -uses: actions/setup-node@v4
     #    with:
     #      node-version: lts/*

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Teste E2E (end-to-end)
        run: yarn run e2e

      # disponibilizando relatorio (artefato)
      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
        

     

       
=======

name: 'Execução Manual'

# Gatilho de execução manual
on:
  workflow_dispatch:

jobs:
  e2e-tests:
    steps: 
     run: yarn
     
     - name: Instalando Playwright
       run: yarn playwright install 

     - name: Testes E2E (end-to-end)
          run: yarn run e2e
     
     - uses: actions/upload-artifact@v4
      with:
        - name: relatorio-de-testes
        path: ./playwright-report


       

       

        - name: Instalando dependências
          run: yarn

        - name: Instalando Playwright
          run: yarn playwright install 
      
        - name: Testes E2E (end-to-end)
          run: yarn run e2e

        -uses  
>>>>>>> 776b55bf544dcb63fec2bfd952d3eb77dbc4126e
