# CI de Nível 03 – Disparo automático sempre que outro for concluído, como deploy

# nome que vai aparecer la nas opções de pipe
name: 'Execução por Deploy'

# triggers OU gatilhos de execucao, regras de disparo de execução 
# gatilho de exec apos outro workflow = workflow_run

on:
  workflow_run:
    workflows: ['Execução Manual']
    types:
      - completed

jobs:
  # descrição do job
  e2e-tests:
    # maquina que job vai executar
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'sucess' }}

    # passo a passo das açoes do job
    steps:
      - uses: actions/checkout@v4

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: lts/*

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Teste E2E (end-to-end)
        run: yarn run e2e

      # disponibilizando relatorio (artefato)
      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report